// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThueXe.Data;

#nullable disable

namespace QuanLyThueXe.Migrations
{
    [DbContext(typeof(QuanLyThueXeDbContext))]
    partial class QuanLyThueXeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyThueXe.Models.BaoDuong", b =>
                {
                    b.Property<int>("MaBaoDuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoDuong"));

                    b.Property<decimal?>("ChiPhi")
                        .HasColumnType("decimal(12,0)");

                    b.Property<string>("DonViThucHien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiBaoDuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNguoiPhuTrach")
                        .HasColumnType("int");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBaoDuong");

                    b.HasIndex("MaNguoiPhuTrach");

                    b.HasIndex("MaXe");

                    b.ToTable("BAO_DUONG");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.CauHinhHeThong", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHinh"));

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KieuDuLieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCauHinh");

                    b.HasIndex("NguoiCapNhat");

                    b.HasIndex("TenKhoa")
                        .IsUnique();

                    b.ToTable("CAU_HINH_HE_THONG");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<bool>("IsHienThi")
                        .HasColumnType("bit");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiAdmin")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaHopDong")
                        .IsUnique();

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaXe");

                    b.ToTable("DANH_GIA");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DmHangXe", b =>
                {
                    b.Property<int>("MaHangXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHangXe"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NuocSanXuat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHangXe");

                    b.ToTable("DM_HANG_XE");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DmLoaiGiayTo", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("DM_LOAI_GIAY_TO");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DmPhongCach", b =>
                {
                    b.Property<int>("MaPhongCach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongCach"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenPhongCach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhongCach");

                    b.ToTable("DM_PHONG_CACH");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DmTinhThanh", b =>
                {
                    b.Property<int>("MaTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinh"));

                    b.Property<int?>("MaVung")
                        .HasColumnType("int");

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTinh");

                    b.ToTable("DM_TINH_THANH");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GiaThueGoc")
                        .HasColumnType("decimal(12,0)");

                    b.Property<decimal>("HeSoMua")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiXacNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraThucTe")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhuPhiTreHan")
                        .HasColumnType("decimal(15,0)");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(15,0)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(15,0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("MaNguoiXacNhan");

                    b.HasIndex("MaXe");

                    b.ToTable("HOP_DONG", t =>
                        {
                            t.HasTrigger("Trigger_HopDong");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuanLyThueXe.Models.HopDongTaiLieu", b =>
                {
                    b.Property<int>("MaTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiLieu"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiFile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTaiLieu");

                    b.HasIndex("MaHopDong");

                    b.ToTable("HOP_DONG_TAI_LIEU");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaLoaiGiayTo")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaTinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoGPLX")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoGiayTo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaLoaiGiayTo");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique()
                        .HasFilter("[MaNguoiDung] IS NOT NULL");

                    b.HasIndex("MaTinh");

                    b.HasIndex("SoGPLX")
                        .IsUnique();

                    b.HasIndex("SoGiayTo")
                        .IsUnique();

                    b.ToTable("KHACH_HANG");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<int>("DaSuDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DieuKienToiThieu")
                        .HasColumnType("decimal(15,0)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GiaTriGiamToiDa")
                        .HasColumnType("decimal(15,0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanSuDung")
                        .HasColumnType("int");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKhuyenMai");

                    b.HasIndex("MaCode")
                        .IsUnique();

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("KHUYEN_MAI");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.LichSuKhuyenMai", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienDuocGiam")
                        .HasColumnType("decimal(15,0)");

                    b.Property<DateTime>("ThoiGianApDung")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaKhuyenMai");

                    b.ToTable("LICH_SU_KHUYEN_MAI");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NGUOI_DUNG");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.PhuPhiMua", b =>
                {
                    b.Property<int>("MaPhuPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuPhi"));

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("HeSoNhan")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhuPhi");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("PHU_PHI_MUA");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NhomQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyen");

                    b.HasIndex("TenQuyen")
                        .IsUnique();

                    b.ToTable("QUYEN");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LoaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiNhanTien")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(15,0)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaNguoiNhanTien");

                    b.ToTable("THANH_TOAN");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("IsDoc")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("MaHopDongLienQuan")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaXeLienQuan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaHopDongLienQuan");

                    b.HasIndex("MaNguoiNhan");

                    b.HasIndex("MaXeLienQuan");

                    b.ToTable("THONG_BAO");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VAI_TRO");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.VaiTroQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("MaVaiTro", "MaQuyen");

                    b.HasIndex("MaQuyen");

                    b.ToTable("VAI_TRO_QUYEN");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.Xe", b =>
                {
                    b.Property<int>("MaXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXe"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DanhGiaTrungBinh")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("DungTich")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaThueNgay")
                        .HasColumnType("decimal(12,0)");

                    b.Property<int>("MaHangXe")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongCach")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamSanXuat")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanThue")
                        .HasColumnType("int");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaXe");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("MaHangXe");

                    b.HasIndex("MaPhongCach");

                    b.ToTable("XE", t =>
                        {
                            t.HasTrigger("Trigger_Xe");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuanLyThueXe.Models.XeHinhAnh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAnhChinh")
                        .HasColumnType("bit");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaXe");

                    b.ToTable("XE_HINH_ANH");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.BaoDuong", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiPhuTrach")
                        .WithMany("BaoDuongs")
                        .HasForeignKey("MaNguoiPhuTrach");

                    b.HasOne("QuanLyThueXe.Models.Xe", "Xe")
                        .WithMany("BaoDuongs")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiPhuTrach");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.CauHinhHeThong", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiCapNhatNavigation")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhat");

                    b.Navigation("NguoiCapNhatNavigation");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DanhGia", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.HopDong", "HopDong")
                        .WithOne("DanhGia")
                        .HasForeignKey("QuanLyThueXe.Models.DanhGia", "MaHopDong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.KhachHang", "KhachHang")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.Xe", "Xe")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("KhachHang");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.HopDong", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.KhachHang", "KhachHang")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("MaKhuyenMai");

                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiTao")
                        .WithMany("HopDongsTao")
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiXacNhan")
                        .WithMany("HopDongsXacNhan")
                        .HasForeignKey("MaNguoiXacNhan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyThueXe.Models.Xe", "Xe")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NguoiTao");

                    b.Navigation("NguoiXacNhan");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.HopDongTaiLieu", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.HopDong", "HopDong")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.DmLoaiGiayTo", "LoaiGiayTo")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaLoaiGiayTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiDung")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyThueXe.Models.KhachHang", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyThueXe.Models.DmTinhThanh", "TinhThanh")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaTinh");

                    b.Navigation("LoaiGiayTo");

                    b.Navigation("NguoiDung");

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.KhuyenMai", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.LichSuKhuyenMai", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("LichSuKhuyenMais")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.PhuPhiMua", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.HopDong", "HopDong")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiNhanTien")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaNguoiNhanTien");

                    b.Navigation("HopDong");

                    b.Navigation("NguoiNhanTien");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.HopDong", "HopDongLienQuan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaHopDongLienQuan");

                    b.HasOne("QuanLyThueXe.Models.NguoiDung", "NguoiNhan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaNguoiNhan");

                    b.HasOne("QuanLyThueXe.Models.Xe", "XeLienQuan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaXeLienQuan");

                    b.Navigation("HopDongLienQuan");

                    b.Navigation("NguoiNhan");

                    b.Navigation("XeLienQuan");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.VaiTroQuyen", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.Xe", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.DmHangXe", "HangXe")
                        .WithMany("Xes")
                        .HasForeignKey("MaHangXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThueXe.Models.DmPhongCach", "PhongCach")
                        .WithMany("Xes")
                        .HasForeignKey("MaPhongCach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangXe");

                    b.Navigation("PhongCach");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.XeHinhAnh", b =>
                {
                    b.HasOne("QuanLyThueXe.Models.Xe", "Xe")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DmHangXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DmLoaiGiayTo", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DmPhongCach", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.DmTinhThanh", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.HopDong", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("TaiLieus");

                    b.Navigation("ThanhToans");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.KhachHang", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.KhuyenMai", b =>
                {
                    b.Navigation("LichSuKhuyenMais");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.NguoiDung", b =>
                {
                    b.Navigation("BaoDuongs");

                    b.Navigation("HopDongsTao");

                    b.Navigation("HopDongsXacNhan");

                    b.Navigation("KhachHang");

                    b.Navigation("ThanhToans");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");

                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("QuanLyThueXe.Models.Xe", b =>
                {
                    b.Navigation("BaoDuongs");

                    b.Navigation("DanhGias");

                    b.Navigation("HinhAnhs");

                    b.Navigation("HopDongs");

                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
